# Generated by Django 5.2.4 on 2025-07-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rifa',
            name='preco_por_numero',
        ),
        migrations.AddField(
            model_name='rifa',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='rifas/'),
        ),
    ]
