# Generated by Django 5.2.4 on 2025-07-22 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0002_remove_rifa_preco_por_numero_rifa_preco_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='encerrada',
            field=models.BooleanField(default=False, help_text='Marque como encerrada para tornar os bilhetes indisponíveis.'),
        ),
        migrations.CreateModel(
            name='NumeroRifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('reservado_em', models.DateTimeField(blank=True, null=True)),
                ('reservado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rifa.rifa')),
            ],
        ),
    ]
