# Generated by Django 5.2.4 on 2025-07-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0003_rifa_encerrada_numerorifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='data_encerramento',
            field=models.DateTimeField(blank=True, help_text='Data e hora de encerramento da rifa.', null=True),
        ),
    ]
