# Generated by Django 5.2.4 on 2025-07-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0004_rifa_data_encerramento'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='ganhador_foto',
            field=models.ImageField(blank=True, help_text='Foto do ganhador.', null=True, upload_to='ganhadores/'),
        ),
        migrations.AddField(
            model_name='rifa',
            name='ganhador_nome',
            field=models.CharField(blank=True, help_text='Nome do ganhador.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rifa',
            name='ganhador_numero',
            field=models.CharField(blank=True, help_text='Número do bilhete sorteado.', max_length=20, null=True),
        ),
    ]
