# Generated by Django 5.2.4 on 2025-07-23 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa', '0005_rifa_ganhador_foto_rifa_ganhador_nome_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numero',
            options={'ordering': ['rifa', 'numero'], 'verbose_name': 'Bilhete', 'verbose_name_plural': 'Bilhetes'},
        ),
        migrations.AddField(
            model_name='numero',
            name='comprador_cpf',
            field=models.CharField(blank=True, max_length=14, verbose_name='CPF do comprador'),
        ),
        migrations.AlterField(
            model_name='numero',
            name='comprador_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail do comprador'),
        ),
        migrations.AlterField(
            model_name='numero',
            name='comprador_nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome do comprador'),
        ),
        migrations.AlterField(
            model_name='numero',
            name='comprador_telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone do comprador'),
        ),
        migrations.AlterField(
            model_name='numero',
            name='numero',
            field=models.PositiveIntegerField(verbose_name='Número do bilhete'),
        ),
        migrations.AlterField(
            model_name='numero',
            name='rifa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros', to='rifa.rifa', verbose_name='Rifa'),
        ),
        migrations.AlterField(
            model_name='numero',
            name='status',
            field=models.CharField(choices=[('livre', 'Livre'), ('reservado', 'Reservado'), ('pago', 'Pago')], default='livre', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterUniqueTogether(
            name='numero',
            unique_together={('rifa', 'numero')},
        ),
    ]
